doctor/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views




urlpatterns = [

    url(r'^$', views.index, name='index'),
    # url(r'^hello/$', views.index, name='hello'), no more "hello function"
    url(r'^(?P<doctor_id>[0-9]+)/$', views.doctor, name='doctor'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^doctors/$', views.doctor_list),
    url(r'^doctors/(?P<pk>[0-9]+)/$', views.doctor_detail),



]

patient/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url
from . import views





urlpatterns = [
    url(r'^$', views.index, name='index'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^doctor/', include('doctor.urls')),
    url(r'^patient/', include('patient.urls')),
    url(r'^doctor/signup/', include('doctor.urls')),
    url(r'^', include('doctor.urls')),

]

doctor/models.py
from __future__ import unicode_literals
from django.db import models

class Doctor(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    specialty = models.CharField(max_length=30) #will choose from a list here
    birthday = models.DateField(null=True, blank=True) #how do I calculate age? 

    def __str__(self):              # __unicode__ on Python 2
        return "%s %s" % (self.first_name, self.last_name)


class Practice(models.Model):

	doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE) #one practice to many doctors
	practice_name = models.CharField(max_length=30)
	practice_type = models.CharField(max_length=30) # can have more than one
	practice_location = models.CharField(max_length=30) # must be better way

patient/models.py
from __future__ import unicode_literals
from django.db import models


class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    birthday = models.DateField(null=True, blank=True) #how do I calculate age? 

    def __str__(self):              # __unicode__ on Python 2
        return "%s %s" % (self.first_name, self.last_name)

doctor/forms.py
from django import forms
from django.forms import ModelForm
from .models import Doctor

#create form from defined model

class DoctorForm(ModelForm):

    class Meta:
    	model = Doctor
    	fields = ['first_name', 'last_name', 'email']

    def __str__(self): #not mandatory

    	return self.name 
    	

doctor/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from .models import Doctor
from .forms import DoctorForm
from .serializers import DoctorSerializer
from django.http import Http404



def signup(request):

	

	if request.method == 'POST':
		form = DoctorForm(request.POST)

		if form.is_valid():

			form = form.save()


			return HttpResponseRedirect('thanks/')

	else:

		form = DoctorForm()

	context = { 

	'form': form

	}

	return render(request, 'doctor/signup.html', context)





def index(request):
    #return HttpResponse("Hello, world. You're at the doctor index.")

    #return render(request, 'doctor/index.html')

    doctor_list = Doctor.objects.order_by('last_name')

    context = {

		 'doctor_list': doctor_list,
	}

    return render(request, 'doctor/index.html', context)


def doctor(request, doctor_id):


	try:

		doctor = Doctor.objects.get(pk=doctor_id)

	except Doctor.DoesNotExist:

		raise Http404("Doctor does not exist")

	return render(request, 'doctor/doctor.html', {'doctor': doctor})

@csrf_exempt   
def doctor_list(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        doctors = Doctor.objects.all()
        serializer = DoctorSerializer(doctors, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = DoctorSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data, status=201)
        return JSONResponse(serializer.errors, status=400)

@csrf_exempt
def doctor_detail(request, pk):
    """
    Retrieve, update or delete a code snippet.
    """
    try:
        doctor = Doctor.objects.get(pk=pk)
    except Doctor.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = DoctorSerializer(doctor)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = DoctorSerializer(doctor, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        doctor.delete()
        return HttpResponse(status=204)












class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """
    def __init__(self, data, **kwargs):
      content = JSONRenderer().render(data)
      kwargs['content_type'] = 'application/json'
      super(JSONResponse, self).__init__(content, **kwargs)

patient/views.py
from django.shortcuts import render
from django.http import HttpResponse


# 

def index(request):
    #return HttpResponse("Hello, world. You're at the patient index.")

    return render(request, 'patient/index.html')

doctor/templates/doctor/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-static-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">

      <!-- Main component for a primary marketing message or call to action -->
      {% block content %}
      {% endblock %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

doctor/templates/doctor/doctor.html
<h3> doctor </h3>




	
		

<h4> {{ doctor.first_name }} {{ doctor.last_name }}

</h4>



	

doctor/templates/doctor/index.html
<h3> test doctor (doctor app) </h3>


{% if doctor_list %}

	<ul>
		{% for doctor in doctor_list%}

			<li> <a href="/doctor/{{ doctor.id }}/"> {{ doctor.first_name }} {{ doctor.last_name }}

</a>

</li>

		{% endfor %}

	</ul>

{% else %}
	<p> Nothing to see here </p>

{% endif %}

doctor/templates/doctor/signup.html
{% extends 'doctor/base.html' %}

{% block content %}

<h1> Sign up </h1>


<div class="row">
	<div class="col-md-5">

		<form class="form-horizontal" method="post" role="form" >

			<div class="form-group">

			    {{ form.first_name.errors }} <!-- what is .errors? -->
			    <label for="{{ form.first_name.id_for_label }}">First Name:</label>
			    <input id="id_first_name" maxlength="30" name="first_name" type="text" class="form-control" />


			</div>

			<div class="form-group">

			    {{ form.last_name.errors }}
			    <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
			    {{ form.last_name }}
			    
			</div>

			<div class="form-group">

			    {{ form.email.errors }} 
			    <label for="{{ form.email.id_for_label }}">E-mail:</label>
			    {{ form.email }}
			    
			</div>

			<input type="submit" value="Submit" />

			{% csrf_token %}

		</form>

	</div>

</div>


{% endblock %}



	

doctor/templates/patient/index.html
<h1> test patient 1 </h1>

templates/doctor/index.html
<h1> test doctor (outside template) </h1>

templates/patient/index.html
<h1> test patient (outside templates) </h1>